server.port: 9966
spring.profiles: default
matthews.security.jwt:
  tokenExpirationTime: 240 # Number of minutes
  refreshTokenExpTime: 360 # Minutes
  tokenIssuer: http://example.com
  tokenSigningKey: changeme
  
# Spring Actuator
# See https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html
# Disable by default all but info

endpoints:
  enabled: false
  info:
    enabled: true
    
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

matthews.users:
     encrypted: false
     adminuser : ${random.value}
     password: ${random.value}
     emailAddress: ${random.value}@unicon.net