# Use root/example as user/password credentials
# Use .env to possibly override JAVA_OPTS and SPRING_BOOT_OPTS

# WORK IN PROGRESS
version: '3'
services:
  openlrw_api:
    container_name: openlrw_bundle
    build:
        context: ..\..\
        dockerfile: .\Dockerfile_bundle
    env_file:
      - .env
    ports:
      - "$SPRING_PORT:9966"
    command: bash "/app/docker-start.sh"